In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
##sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
##define the vocabulary size
voc_size=10000

In [20]:
##one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2727, 7466, 7359, 2477],
 [2727, 7466, 7359, 6434],
 [2727, 9937, 7359, 8530],
 [2119, 3073, 8656, 7027, 5501],
 [2119, 3073, 8656, 7027, 6556],
 [9432, 2727, 2929, 7359, 5737],
 [1479, 4111, 4707, 7027]]

In [21]:
##Word embedding representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential



In [22]:
import numpy as np
import pandas as pd

In [23]:
sent_len=8

In [24]:
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
embedded_docs


array([[   0,    0,    0,    0, 2727, 7466, 7359, 2477],
       [   0,    0,    0,    0, 2727, 7466, 7359, 6434],
       [   0,    0,    0,    0, 2727, 9937, 7359, 8530],
       [   0,    0,    0, 2119, 3073, 8656, 7027, 5501],
       [   0,    0,    0, 2119, 3073, 8656, 7027, 6556],
       [   0,    0,    0, 9432, 2727, 2929, 7359, 5737],
       [   0,    0,    0,    0, 1479, 4111, 4707, 7027]])

In [25]:
##feature representation
dim=10

In [26]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 85ms/step


array([[[ 0.04517548, -0.04588911,  0.00274549,  0.01701255,
          0.02241119, -0.03175725,  0.01188161, -0.02253125,
          0.02934858, -0.0423733 ],
        [ 0.04517548, -0.04588911,  0.00274549,  0.01701255,
          0.02241119, -0.03175725,  0.01188161, -0.02253125,
          0.02934858, -0.0423733 ],
        [ 0.04517548, -0.04588911,  0.00274549,  0.01701255,
          0.02241119, -0.03175725,  0.01188161, -0.02253125,
          0.02934858, -0.0423733 ],
        [ 0.04517548, -0.04588911,  0.00274549,  0.01701255,
          0.02241119, -0.03175725,  0.01188161, -0.02253125,
          0.02934858, -0.0423733 ],
        [-0.03347383, -0.03936075,  0.01554313, -0.02616414,
          0.02604688,  0.00146313,  0.02450367,  0.00279492,
          0.03566274,  0.01946929],
        [-0.03907019,  0.03121693,  0.04050482, -0.01716166,
          0.00817151, -0.04573295,  0.04808954, -0.0269124 ,
         -0.03554145,  0.01835492],
        [ 0.00367653,  0.00166618,  0.01061474, -0.0

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0, 2727, 7466, 7359, 2477])

In [30]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 38ms/step


array([[ 0.04517548, -0.04588911,  0.00274549,  0.01701255,  0.02241119,
        -0.03175725,  0.01188161, -0.02253125,  0.02934858, -0.0423733 ],
       [ 0.04517548, -0.04588911,  0.00274549,  0.01701255,  0.02241119,
        -0.03175725,  0.01188161, -0.02253125,  0.02934858, -0.0423733 ],
       [ 0.04517548, -0.04588911,  0.00274549,  0.01701255,  0.02241119,
        -0.03175725,  0.01188161, -0.02253125,  0.02934858, -0.0423733 ],
       [ 0.04517548, -0.04588911,  0.00274549,  0.01701255,  0.02241119,
        -0.03175725,  0.01188161, -0.02253125,  0.02934858, -0.0423733 ],
       [-0.03347383, -0.03936075,  0.01554313, -0.02616414,  0.02604688,
         0.00146313,  0.02450367,  0.00279492,  0.03566274,  0.01946929],
       [-0.03907019,  0.03121693,  0.04050482, -0.01716166,  0.00817151,
        -0.04573295,  0.04808954, -0.0269124 , -0.03554145,  0.01835492],
       [ 0.00367653,  0.00166618,  0.01061474, -0.03859083, -0.04432988,
        -0.01423818,  0.01951864, -0.04890823